/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Tip as PrismaTip,
  PaymentTransaction as PrismaPaymentTransaction,
} from "@prisma/client";

export class TipServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TipCountArgs, "select">): Promise<number> {
    return this.prisma.tip.count(args);
  }

  async tips<T extends Prisma.TipFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TipFindManyArgs>
  ): Promise<PrismaTip[]> {
    return this.prisma.tip.findMany<Prisma.TipFindManyArgs>(args);
  }
  async tip<T extends Prisma.TipFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TipFindUniqueArgs>
  ): Promise<PrismaTip | null> {
    return this.prisma.tip.findUnique(args);
  }
  async createTip<T extends Prisma.TipCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TipCreateArgs>
  ): Promise<PrismaTip> {
    return this.prisma.tip.create<T>(args);
  }
  async updateTip<T extends Prisma.TipUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TipUpdateArgs>
  ): Promise<PrismaTip> {
    return this.prisma.tip.update<T>(args);
  }
  async deleteTip<T extends Prisma.TipDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TipDeleteArgs>
  ): Promise<PrismaTip> {
    return this.prisma.tip.delete(args);
  }

  async getPaymentTransaction(
    parentId: string
  ): Promise<PrismaPaymentTransaction | null> {
    return this.prisma.tip
      .findUnique({
        where: { id: parentId },
      })
      .paymentTransaction();
  }
}
