/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { OrderUpdateManyWithoutBillsInput } from "./OrderUpdateManyWithoutBillsInput";
import { PaymentTransactionUpdateManyWithoutBillsInput } from "./PaymentTransactionUpdateManyWithoutBillsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class BillUpdateInput {
  @ApiProperty({
    required: false,
    type: () => OrderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OrderWhereUniqueInput)
  @IsOptional()
  @Field(() => OrderWhereUniqueInput, {
    nullable: true,
  })
  order?: OrderWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutBillsInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutBillsInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutBillsInput, {
    nullable: true,
  })
  orders?: OrderUpdateManyWithoutBillsInput;

  @ApiProperty({
    required: false,
    type: () => PaymentTransactionUpdateManyWithoutBillsInput,
  })
  @ValidateNested()
  @Type(() => PaymentTransactionUpdateManyWithoutBillsInput)
  @IsOptional()
  @Field(() => PaymentTransactionUpdateManyWithoutBillsInput, {
    nullable: true,
  })
  paymentTransactions?: PaymentTransactionUpdateManyWithoutBillsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  qrCode?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { BillUpdateInput as BillUpdateInput };
